export default function useCountries() {
  return [
    { name: "Afghánistán", code: "af" },
    { name: "Albánie", code: "al" },
    { name: "Alžírsko", code: "dz" },
    { name: "Andorra", code: "ad" },
    { name: "Anglie", code: "gb-eng" },
    { name: "Angola", code: "ao" },
    { name: "Argentina", code: "ar" },
    { name: "Arménie", code: "am" },
    { name: "Austrálie", code: "au" },
    { name: "Ázerbájdžán", code: "az" },
    { name: "Bahrajn", code: "bh" },
    { name: "Belgie", code: "be" },
    { name: "Bělorusko", code: "by" },
    { name: "Bosna a Hercegovina", code: "ba" },
    { name: "Brazílie", code: "br" },
    { name: "Bulharsko", code: "bg" },
    { name: "Černá Hora", code: "me" },
    { name: "Česko", code: "cz" },
    { name: "Čína", code: "cn" },
    { name: "Dánsko", code: "dk" },
    { name: "Ekvádor", code: "ec" },
    { name: "Egypt", code: "eg" },
    { name: "Estonsko", code: "ee" },
    { name: "Finsko", code: "fi" },
    { name: "Francie", code: "fr" },
    { name: "Ghana", code: "gh" },
    { name: "Gibraltar", code: "gi" },
    { name: "Gruzie", code: "ge" },
    { name: "Chorvatsko", code: "hr" },
    { name: "Indie", code: "in" },
    { name: "Irsko", code: "ie" },
    { name: "Island", code: "is" },
    { name: "Itálie", code: "it" },
    { name: "Izrael", code: "il" },
    { name: "Japonsko", code: "jp" },
    { name: "Jihoafrická republika", code: "za" },
    { name: "Jižní Korea", code: "kr" },
    { name: "Kamerun", code: "cm" },
    { name: "Kanada", code: "ca" },
    { name: "Katar", code: "qa" },
    { name: "Kazachstán", code: "kz" },
    { name: "Kolumbie", code: "co" },
    { name: "Kostarika", code: "cr" },
    { name: "Kypr", code: "cy" },
    { name: "Litva", code: "lt" },
    { name: "Lotyšsko", code: "lv" },
    { name: "Lucembursko", code: "lu" },
    { name: "Maďarsko", code: "hu" },
    { name: "Makedonie", code: "mk" },
    { name: "Malta", code: "mt" },
    { name: "Maroko", code: "ma" },
    { name: "Mexiko", code: "mx" },
    { name: "Moldavsko", code: "md" },
    { name: "Monako", code: "mc" },
    { name: "Německo", code: "de" },
    { name: "Nigérie", code: "ng" },
    { name: "Nizozemsko", code: "nl" },
    { name: "Norsko", code: "no" },
    { name: "Nový Zéland", code: "nz" },
    { name: "Omán", code: "om" },
    { name: "Paraguay", code: "py" },
    { name: "Peru", code: "pe" },
    { name: "Polsko", code: "pl" },
    { name: "Portugalsko", code: "pt" },
    { name: "Pobřeží slonoviny", code: "ci" },
    { name: "Rakousko", code: "at" },
    { name: "Rumunsko", code: "ro" },
    { name: "Rusko", code: "ru" },
    { name: "Řecko", code: "gr" },
    { name: "San Marino", code: "sm" },
    { name: "Saúdská Arábie", code: "sa" },
    { name: "Senegal", code: "sn" },
    { name: "Severní Irsko", code: "gb-nir" },
    { name: "Singapur", code: "sg" },
    { name: "Skotsko", code: "gb-sct" },
    { name: "Slovensko", code: "sk" },
    { name: "Slovinsko", code: "si" },
    { name: "Spojené arabské emiráty", code: "ae" },
    { name: "USA", code: "us" },
    { name: "Srbsko", code: "rs" },
    { name: "Španělsko", code: "es" },
    { name: "Švédsko", code: "se" },
    { name: "Švýcarsko", code: "ch" },
    { name: "Thajsko", code: "th" },
    { name: "Tunisko", code: "tn" },
    { name: "Turecko", code: "tr" },
    { name: "Ukrajina", code: "ua" },
    { name: "Uruguay", code: "uy" },
    { name: "Velká Británie", code: "gb" },
    { name: "Venezuela", code: "ve" },
    { name: "Vietnam", code: "vn" },
    { name: "Wales", code: "gb-wls" }
  ]
}