export default function useTeams() {
  return [
    { name: "AC Milan", code: "/ucl/ac-milan" },
    { name: "Arsenal", code: "/ucl/arsenal" },
    { name: "Aston Villa", code: "/ucl/aston-villa" },
    { name: "Atalanta", code: "/ucl/atalanta" },
    { name: "Atlético Madrid", code: "/ucl/atletico-madrid" },
    { name: "Barcelona", code: "/ucl/barcelona" },
    { name: "Bayer Leverkusen", code: "/ucl/bayer-leverkusen" },
    { name: "Bayern Munich", code: "/ucl/bayern-munich" },
    { name: "Benfica", code: "/ucl/benfica" },
    { name: "Borussia Dortmund", code: "/ucl/borussia-dortmund" },
    { name: "Bologna", code: "/ucl/bologna" },
    { name: "Brest", code: "/ucl/brest" },
    { name: "Celtic", code: "/ucl/celtic" },
    { name: "Club Brugge", code: "/ucl/club-brugge" },
    { name: "Crvena Zvezda", code: "/ucl/crvena-zvezda" },
    { name: "Dinamo Zagreb", code: "/ucl/dinamo-zagreb" },
    { name: "Feyenoord", code: "/ucl/feyenoord" },
    { name: "Girona", code: "/ucl/girona" },
    { name: "Inter Milan", code: "/ucl/inter-milan" },
    { name: "Juventus", code: "/ucl/juventus" },
    { name: "Lille", code: "/ucl/lille" },
    { name: "Liverpool", code: "/ucl/liverpool" },
    { name: "Manchester City", code: "/ucl/manchester-city" },
    { name: "Monaco", code: "/ucl/monaco" },
    { name: "PSG", code: "/ucl/psg" },
    { name: "PSV Eindhoven", code: "/ucl/psv-eindhoven" },
    { name: "RB Leipzig", code: "/ucl/rb-leipzig" },
    { name: "Real Madrid", code: "/ucl/real-madrid" },
    { name: "Salzburg", code: "/ucl/salzburg" },
    { name: "Slovan Bratislava", code: "/ucl/slovan-bratislava" },
    { name: "Shakhtar Donetsk", code: "/ucl/shakhtar-donetsk" },
    { name: "Sparta Praha", code: "/ucl/sparta-praha" },
    { name: "Sporting CP", code: "/ucl/sporting-cp" },
    { name: "Sturm Graz", code: "/ucl/sturm-graz" },
    { name: "VfB Stuttgart", code: "/ucl/vfb-stuttgart" },
    { name: "Young Boys", code: "/ucl/young-boys" },

    { name: "Viktoria Plzeň", code: "/el/viktoria-plzen" },
    { name: "Slavia Praha", code: "/el/slavia-praha" },
    { name: "Frankurt", code: "/el/frankurt" },
    { name: "Ludogorec", code: "/el/ludogorec" },
    { name: "Ajax", code: "/el/ajax" },
    { name: "PAOK", code: "/el/paok" },
    { name: "Athletic Bilbao", code: "/el/athletic-bilbao" },
    { name: "Real Sociedad", code: "/el/real-sociedad" },
    { name: "Dynamo Kyiv", code: "/el/dynamo-kyiv" },
    { name: "Fenerbahçe", code: "/el/fenerbahce" },
    { name: "Anderlecht", code: "/el/anderlecht" },
    { name: "Malmö", code: "/el/malmo" },
    { name: "Manchester United", code: "/el/manchester-united" },
  ]
}